### ISSUE TITLE
Please provide static executables

### ISSUE THREAD

**Issue by mscook** [Victorian-Bioinformatics-Consortium/snippy#2]
uqmstan1@barrine2:~/Beatson_shared/bin/snippy/1.4/binaries/linux> ./bcftools
./bcftools: /lib64/libz.so.1: no version information available (required by ./bcftools)
./bcftools: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bcftools)
./bcftools: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./bcftools)

uqmstan1@barrine2:~/Beatson_shared/bin/snippy/1.4/binaries/linux> ./bwa
./bwa: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bwa)
./bwa: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./bwa)

./freebayes: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./freebayes)
./freebayes: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./freebayes)
./freebayes: /sw/gcc/4.5.2/lib64/gcc/x86_64-suse-linux/4.5.2/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./freebayes)

uqmstan1@barrine2:~/Beatson_shared/bin/snippy/1.4/binaries/linux> ./samtools
./samtools: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

uqmstan1@barrine2:~/Beatson_shared/bin/snippy/1.4/binaries/linux> ./vcfstreamsort
./vcfstreamsort: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./vcfstreamsort)
./vcfstreamsort: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./vcfstreamsort)
./vcfstreamsort: /sw/gcc/4.5.2/lib64/gcc/x86_64-suse-linux/4.5.2/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./vcfstreamsort)

uqmstan1@barrine2:~/Beatson_shared/bin/snippy/1.4/binaries/linux> ./vcfuniq
./vcfuniq: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./vcfuniq)
./vcfuniq: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./vcfuniq)
./vcfuniq: /sw/gcc/4.5.2/lib64/gcc/x86_64-suse-linux/4.5.2/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./vcfuniq)

**Comment by tseemann** [comment]
I tried to create static binaries a few times, but kept running into 'nss' issues. It seems it is IMPOSSIBLE on modern GNU libc based systems to have a true static linked binary.

http://stackoverflow.com/questions/3430400/linux-static-linking-is-dead

Ideally we would get all these tools into Homebrew / Linuxbrew / Debian MED / BioRPMs to solve the problem (for some people).

If you have any other ideas, I'd appreciate it!

I'm assuming your GLIBC is quite old - mine is pretty old (Ubuntu 12.04 LTS).

Torst

**Comment by tseemann** [comment]
Best solution is to upgrade your Linux distribution or pester your sysadmin to install the dependencies.
