### ISSUE TITLE
vcf-consensus option

### ISSUE THREAD

**Issue by kwongj** [Victorian-Bioinformatics-Consortium/snippy#3]
It would be useful to have a vcf-consensus option built in:
$ bgzip snps.vcf
$ tabix -p vcf snps.vcf.gz
$ vcf-consensus snps.vcf.gz < ref.fa > new.fa

**Comment by tseemann** [comment]
This is now done by default. The output file is called "consensus.fa". See commit https://github.com/Victorian-Bioinformatics-Consortium/snippy/commit/01a095f8e3b6e7b88148ffe2056d0f565722ace9
